init. post member(sign up)
hj-develop-study/dang-clone-coding-backend pull request #9
Opened 2022-03-05 06:59 UTC by dearseul

1. repositoy
2. service

2022-03-05 08:53 UTC, JamieShin0201 requested changes
수고하셨습니다 :D 

몇 가지 코멘트 남겼습니다. 시간 되실 때 확인 부탁드려요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/repository/MemberRepository.java
> +
불필요한 공백입니다.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/controller/MemberController.java
> +@AllArgsConstructor
중요한 어노테이션을 클래스 가까이두면 더 좋을 거 같습니다.

AllArgsConstructor 대신 인스턴스 변수를 final 로 하고 RequiredArgsConstructor 를 사용해도 괜찮을 거 같아요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/controller/MemberController.java
> +    @PostMapping("member")
url 를 전에 이야기 했던 것처럼 `/api/members` 로 하면 좋을 거 같아요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/repository/MemberRepository.java
> +public class MemberRepository {
`Spring Data JPA` 에 있는 `JpaRepository` 를 상속받아 구현하면 더 편리할 거 같아요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/repository/MemberRepository.java
> +        return em.createQuery("select m from Member m where m.id = :id", Member.class)
`id` 는 primary key 여서 `id` 로 조회하면 해당하는 회원이 없거나 한명일 거 같아요. 

즉, `Optional<Member>` 를 반환하는게 좋아보여요. 

`em.find()` 를 이용할 수 있겠네요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/service/MemberService.java
> +        validateDuplicateMember(member); // 중복 회원 검증
함수명으로 충분히 설명이 되는 것들은 주석들 달지 않아도 될 거 같아요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/controller/MemberController.java
> +    public void signup(Member member) {
Member 말고 회원 가입용 Dto를 만들어 필요한 정보만 받고 유효성 검증을 할 수 있겠네요.

2022-03-05 08:53 UTC, JamieShin0201 commented on src/main/java/com/daangn/member/service/MemberService.java
> +        List<Member> findMembers = memberRepository.findById(member.getId());
`email` 로 중복회원을 검증해야할 거 같아요.

2022-03-05 17:52 UTC, Jaeeun1083 reviewed
수고하셨습니다! 수정사항 반영하신 이후 approve하면 될까요?

2022-03-06 01:20 UTC, dearseul commented
코멘트 감사합니다~ 넵넵

2022-03-06 15:25 UTC, dearseul commented
회사에서도 보려고 커밋해둡니다.
너무 더러워서 완성되면 이건 닫고 새로 pr열게요.

2022-03-15 08:20 UTC, merged